apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-metrics-app
  template:
    metadata:
      labels:
        app: http-metrics-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000    # A non-root user
        fsGroup: 1000      # Ensures files are accessible by this user
      containers:
      - name: http-metrics-app
        image: http-metrics-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000  # Ensures the container does not run as root
          allowPrivilegeEscalation: false  # Prevents privilege escalation