apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-request-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-metrics-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_request_count
      target:
        type: AverageValue
        averageValue: 50

